// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DayCounterController from "./day_counter_controller"
application.register("day-counter", DayCounterController)

import DropdownSearchController from "./dropdown_search_controller"
application.register("dropdown-search", DropdownSearchController)

import FilterHighlightController from "./filter_highlight_controller"
application.register("filter-highlight", FilterHighlightController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FriendPhotosPopupController from "./friend_photos_popup_controller"
application.register("friend-photos-popup", FriendPhotosPopupController)

import FriendsPhotosSlideshowController from "./friends_photos_slideshow_controller"
application.register("friends-photos-slideshow", FriendsPhotosSlideshowController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LandingPageSlidersController from "./landing_page_sliders_controller"
application.register("landing-page-sliders", LandingPageSlidersController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchFieldController from "./search_field_controller"
application.register("search-field", SearchFieldController)

import VideoControlController from "./video_control_controller"
application.register("video-control", VideoControlController)
